node:
  name: local-dev-node

qemu:
  binary: qemu-system-x86_64
  machine:
    type: q35
    accelerator: tcg
  cpuModel: ""
  firmware:
    biosPath: ""
  runtime:
    qmpSocket: .tmp/qemu/cirros/qmp.sock
    pidFile: .tmp/qemu/cirros/qemu.pid
    qemuLog: .tmp/qemu/cirros/qemu.log
    serialLog: .tmp/qemu/cirros/serial.log

qmp:
  socketDir: .tmp/qemu

network:
  bridge: govirta0
  tap: gv-tap0
